on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install-zola
        uses: https://github.com/taiki-e/install-action@zola
      - name: install-lftp
        run: sudo apt-get update && sudo apt-get install lftp
      - name: build
        run: zola build
      - name: check
        run: zola check
      - name: deploy
        run: |
          echo ${{ secrets.SFTP_HOST_KEYS }} >> $HOME/.ssh/known_hosts
          lftp -c "open ${{ secrets.SFTP_URL }} && mirror -Rev public /"
