name: Deploy to GitHub Pages

on:
  pull_request:
    types: [closed]
    branches: ["main"]

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/jaspr'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
